name: textlint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  textlint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - run: corepack enable pnpm
    - name: Install deps
      run: npx pnpm i
    - name: Run textlint
      run: npm run lint
